### ISSUE TITLE
Communication Inclusivity: Alternatives Question

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#163] opened 2019-02-18 20:54 UTC
Again, this question is not clear

**Comment by emmairwin** [comment] 2019-02-27 22:17
Can you say more about this issue?

**Comment by germonprez** [comment] 2019-02-28 01:36
Sorry @emmairwin -- Just saying that a question is needed. I just put notes on here as I was aligning with the metrics repository

**Comment by geekygirldawn** [comment] 2019-03-03 11:17
This is a duplicate of #109. The question isn't clear because we haven't developed a question or the resource page for the [Communication Inclusivity: Alternatives](https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/communication/communication-inclusivity-alternatives.md) metric :)

**Closed by geekygirldawn** 2019-03-03 11:17 UTC
