### ISSUE TITLE
Contribution Type

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-diversity-inclusion#165] opened 2019-02-18 21:21 UTC
There are two Contribution Type metrics in the D&I focus areas: 

https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/recognition/contribution-type.md

and 

https://github.com/chaoss/wg-diversity-inclusion/blob/master/focus-areas/contribution/contribution-type.md

**Comment by GeorgLink** [comment] 2019-02-19 20:02
Thanks @germonprez 

Closing because it's duplicate of #122

**Closed by GeorgLink** 2019-02-19 20:02 UTC
